In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [112]:
def retrieve_dataframes(ticker):
    bs=ticker.quarterly_balancesheet
    fi=ticker.quarterly_financials
    cf=ticker.quarterly_cashflow
    earnings=ticker.quarterly_earnings
    history=ticker.history(period='2y')

    bs.insert(0,'Stock',ticker.ticker)
    fi.insert(0,'Stock',ticker.ticker)
    cf.insert(0,'Stock',ticker.ticker)
    earnings.insert(0,'Stock',ticker.ticker)
    history.insert(0,'Stock',ticker.ticker)

    bs=bs.reset_index()
    fi=fi.reset_index()
    cf=cf.reset_index()
    earnings=earnings.reset_index()
    history=history.reset_index()
    return [bs,fi,cf,earnings,history]

def merge(dfset1, dfset2):
    result=[]
    for i in range(len(dfset1)):
        df=pd.concat([dfset1[i],dfset2[i]],axis=0)
        result.append(df)
    return result

def savecsv(dfset):
    (bs,fi,cf,earnings,history)=(dfset[0],dfset[1],dfset[2],dfset[3],dfset[4])
    bs.to_csv("bs.csv")
    fi.to_csv("fi.csv")
    cf.to_csv("cf.csv")
    earnings.to_csv("earnings.csv")
    history.to_csv("history.csv")

In [113]:
mytickers=yf.Tickers("BAC MSFT")

In [114]:
all_result=[pd.DataFrame(),pd.DataFrame(),pd.DataFrame(),pd.DataFrame(),pd.DataFrame()]
for myticker in mytickers.tickers:
    all_result = merge(all_result,retrieve_dataframes(myticker))
    
savecsv(all_result)

In [130]:
t = yf.Ticker("BAC")
fi=t.quarterly_financials

In [131]:
fi

,2020-06-30,2020-03-31,2019-12-31,2019-09-30
Research Development,None,None,None,None
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,3.799e+09,4.531e+09,8.169e+09,6.859e+09
Minority Interest,None,None,None,None
Net Income,3.533e+09,4.01e+09,6.994e+09,5.777e+09
Selling General Administrative,1.1934e+10,1.2065e+10,1.1785e+10,1.1431e+10
Gross Profit,1.7209e+10,1.8006e+10,2.1408e+10,1.9956e+10
Ebit,0,0,0,0
Operating Income,3.799e+09,4.531e+09,8.85e+09,6.859e+09
Other Operating Expenses,1.476e+09,1.41e+09,7.73e+08,1.666e+09
Interest Expense,None,None,None,None
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,2.66e+08,5.21e+08,1.175e+09,1.082e+09
Total Revenue,1.7209e+10,1.8006e+10,2.1408e+10,1.9956e+10
Total Operating Expenses,1.341e+10,1.3475e+10,1.2558e+10,1.3097e+10
Cost Of Revenue,0,0,0,0
Total Other Income Expense Net,0,0,-6.81e+08,0
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,3.533e+09,4.01e+09,6.994e+09,5.777e+09
Net Income Applicable To Common Shares,3.284e+09,3.541e+09,6.748e+09,5.272e+09